# Generated by Django 3.2.8 on 2021-10-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='review',
            name='owner',
        ),
    ]
